# Generated by Django 3.2.5 on 2021-11-24 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('rotativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(blank=True, unique=True)),
                ('legajo', models.IntegerField(blank=True, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.areamodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(blank=True, unique=True)),
                ('legajo', models.IntegerField(blank=True, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.areamodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
